<?php
/**
 * GameCommerce Theme
 * @var Mage_Page_Block_Html_Header $this
 **/
?>
<script> console.log("Hello World") </script>
<div class="main-header">
    <div class="top-header">
        <div class="store-language-container">
            <?php echo $this->getChildHtml('store_language') ?>
        </div>

        <?php echo $this->getChildHtml('currency_switcher') ?>

        <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getChildHtml('accountLinks') ?></p>
    </div>

    <header id="header" class="header">
            <div class="row">
                <div class="col-md-4">
                    <a class="logo" href="<?php echo $this->getUrl('') ?>">
                        <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="large" />
                    </a>
                </div>
                <div class="col-md-4 navigator">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->getUrl('') ?>">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->getUrl('')."about" ?>">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->getUrl('')."games" ?>">Games</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->getUrl('')."contacts" ?>">Contact</a>
                        </li>
                        <li class="nav-item dropdown">
                                <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
                                <div id="header-account" class="dropdown-menu">
                                    <?php echo $this->getChildHtml('topLinks') ?>
                                </div>                           
                        </li>
                    </ul>
                </div>
            
                <div class="col-md-4 search">
                    <?php echo $this->getChildHtml('topSearch') ?>
                    <?php echo $this->getChildHtml('minicart_head'); ?>                
                </div>
            </div>
    </header>
</div>

<?php echo $this->getChildHtml('topContainer'); ?>
