<div class="featured-divider" >
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 90">
            <title>Asset 1</title>
            <g id="b579fca7-3fcf-4c40-a2ac-b61362b668c1" data-name="Layer 2">
                <g id="abcf6512-551c-40d4-8355-f95f25e8a0a2" data-name="Layer 1">
                    <path d="M761.9,39.6,643.1,23,333.9,92.8.1,0H0V99H1000V0Z" fill="#1b262c"/>
                </g>
            </g>
        </svg>
    </div>